// rock-n-roll-ng-lazy/src/app/musicians/musicians.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { Store } from 'juliette';
import { MusiciansAppState } from './store';
import { fromMusicians } from './store';
import { FormControl } from '@angular/forms';
import { debounceTime, distinctUntilChanged, takeUntil } from 'rxjs/operators';
import { Subject } from 'rxjs';

@Component({
  selector: 'rnr-musicians',
  templateUrl: './musicians.component.html',
})
export class MusiciansComponent implements OnInit, OnDestroy {
  private destroy = new Subject();

  searchTermControl = new FormControl();
  musiciansState$ = this.store.select(fromMusicians.featureKey);

  constructor(private store: Store<MusiciansAppState>) {}

  ngOnInit(): void {
    this.store.dispatch(fromMusicians.fetchMusicians());

    this.searchTermControl.valueChanges
      .pipe(debounceTime(300), distinctUntilChanged(), takeUntil(this.destroy))
      .subscribe(searchTerm => this.store.dispatch(fromMusicians.updateSearchTerm({ searchTerm })));
  }

  onUpdateSelectedPageSize(selectedPageSize: number): void {
    this.store.dispatch(fromMusicians.updateSelectedPageSize({ selectedPageSize }));
  }

  ngOnDestroy(): void {
    this.destroy.next();
  }
}

<ng-container *ngIf="musiciansState$ | async as state">
  <h1>🤘 Musicians</h1>
  <input type="text" [formControl]="searchTermControl" placeholder="🔎" />

  <h1 *ngIf="state.loading; else musiciansList">🎠</h1>
  <ng-template #musiciansList>
    <ul>
      <li *ngFor="let musician of state.musicians">{{ musician.name }} {{ musician.weapon }}</li>
    </ul>
  </ng-template>

  <div class="buffer-top">
    <button
      *ngFor="let pageSize of state.pageSizes"
      (click)="onUpdateSelectedPageSize(pageSize)"
      [class.selected]="pageSize === state.selectedPageSize"
    >
      {{ pageSize }}
    </button>
  </div>
</ng-container>

// rock-n-roll-react/src/containers/Musicians.tsx
import React, { useCallback, useEffect } from 'react';
import { AppState } from '../store';
import { fromMusicians } from '../store/handlers';
import { useDispatch, useSelect } from 'juliette-react';

function Musicians() {
  const state = useSelect<AppState, fromMusicians.State>(fromMusicians.featureKey);
  const dispatch = useDispatch();

  const onUpdateSearchTerm = useCallback(
    (searchTerm: string) => dispatch(fromMusicians.updateSearchTerm({ searchTerm })),
    [dispatch],
  );

  const onUpdateSelectedPageSize = useCallback(
    (selectedPageSize: number) =>
      dispatch(fromMusicians.updateSelectedPageSize({ selectedPageSize })),
    [dispatch],
  );

  useEffect(() => dispatch(fromMusicians.fetchMusicians()), [dispatch]);

  return (
    <div>
      <h1>🤘 Musicians</h1>
      <input
        type="text"
        onChange={event => onUpdateSearchTerm(event.target.value)}
        placeholder="🔎"
      />

      {state.loading ? (
        <h1>🎠</h1>
      ) : (
        <ul>
          {state.musicians.map((musician, i) => (
            <li key={i}>
              {musician.name} {musician.weapon}
            </li>
          ))}
        </ul>
      )}

      <div className="buffer-top">
        {state.pageSizes.map((pageSize, i) => (
          <button
            key={i}
            className={pageSize === state.selectedPageSize ? 'selected' : ''}
            onClick={() => onUpdateSelectedPageSize(pageSize)}
          >
            {pageSize}
          </button>
        ))}
      </div>
    </div>
  );
}

export default Musicians;
